micronaut:
  application:
    name: example

  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
      keys:
        enabled: true
        path: /.well-known/jwks.json
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              jws-algorithm: RS256

datasources:
  default:
    url: ${JDBC_URL:`jdbc:postgresql://localhost/example-jwks`}
    username: ${JDBC_USER:postgres}
    password: ${JDBC_PASSWORD:postgres}
    driverClassName: ${JDBC_DRIVER:org.postgresql.Driver}

jpa:
  default:
    packages-to-scan:
      - 'io.github.aretche.domain'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true